version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: blogapi
      MYSQL_ROOT_PASSWORD: Mysql@143
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog-network

  app:
    build: .
    container_name: blog-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blogapi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mysql@143
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "5457:5457"
    networks:
      - blog-network

volumes:
  mysql_data:

networks:
  blog-network:
